//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldParkingVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos
    {
        public int idDocumentos { get; set; }
        public int Persona { get; set; }
        public int TipoDocumento { get; set; }
        public string NoDocumento { get; set; }
    
        public virtual personas personas { get; set; }
        public virtual tipodocumento tipodocumento1 { get; set; }
    }
}
