//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldParkingVol1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class facturacion
    {
        public int NumeroFactura { get; set; }
        public int IdVehiculo { get; set; }
        public int IdPersona { get; set; }
        [Display(Name ="ENTRADA")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_enrtada { get; set; }
        [Display(Name = "SALIDA")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha_salida { get; set; }
        [Display(Name = "OBSERVACIONES")]
        public string DetalleObservaciones { get; set; }
        [Display(Name = "BAHIA")]
        public int Bahia { get; set; }
        [Display(Name ="FACTURADO")]
        public bool FacturaPermanente { get; set; }
    
        public virtual bahias bahias { get; set; }
        public virtual vehiculos vehiculos { get; set; }
        public virtual personas personas { get; set; }
    }
}
