//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldParkingVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historicovehiculos
    {
        public int idHistoricoVehiculos { get; set; }
        public string Placa { get; set; }
        public int Color { get; set; }
        public int Modelo { get; set; }
        public int Marca { get; set; }
        public int TIpoVehiculo { get; set; }
        public System.DateTime FechaEdicion { get; set; }
    }
}
