//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldParkingVol1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personas()
        {
            //this.documentos = new HashSet<documentos>();
            this.facturacion = new HashSet<facturacion>();
            this.telefonodetalle = new HashSet<telefonodetalle>();
        }
    
        public int idPersonas { get; set; }
        [Required (ErrorMessage = "Campo Nombre Requerido"), Display(Name = "Nombres")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Campo Correo Requerido"), EmailAddress(ErrorMessage = "Correo Invaldo Ejem@Ejemp.com")]
        public string Correo { get; set; }
        [Required(ErrorMessage = "Campo Direccion Requerido")]
        public string Direccion { get; set; }
        [Display(Name ="Rol")]
        public int Rol { get; set; }
        [Display(Name ="Estado")]
        public bool Activo { get; set; }
        [Display(Name ="Sexo")]
        public int CodSexo { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<documentos> documentos { get; set; }
        [ForeignKey("Persona")]
        public virtual documentos documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturacion> facturacion { get; set; }
        public virtual roles roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telefonodetalle> telefonodetalle { get; set; }
        public virtual sexo sexo { get; set; }
    }
}
